export default {
    denali: {
        name: 'Denali',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['summary', 'portfolio', 'text_story', 'dated_stories', 'strengths'],
        strengths: 'stripes',
        new: true,
        styles: {
            '@header-font': 'montserrat',
            '@body-font': 'montserrat',
            '@primary': '#182d34',
            '@secondary': '#f5cc07',
            '@link': '#f5cc07',
            '@background': '#ffffff',
            '@body-font-size': '16px',
            '@section-margins': '2.5em',
            '@article-margins': '2.0em',
        },
        fixedStyles: {
            '@article-spacing': '160%',
            '@article-horizontal-spacing': '0.6em',
            '@horizontal-spacing': '1.5em',
            '@header-height': '15em',
            '@body': '#6b6b6b',
            '@subtle': 'rgba(107, 107, 107, 0.05)',
            '@faint': '#c2d1d9',
            '@competency-size': '3px',
            '@competency-style': 'dashes',
        },
    },
    rainier: {
        name: 'Rainier',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['summary', 'portfolio', 'text_story', 'strengths'],
        strengths: 'stripes',
        new: true,
        styles: {
            '@header-font': 'arvo',
            '@body-font': 'lato',
            '@primary': '#32d74b',
            '@secondary': '#f2f5f7',
            '@link': '#1aa92f',
            '@background': '#ffffff',
            '@body-font-size': '16px',
            '@section-margins': '2.5em',
            '@article-margins': '2.0em',
            '@bg-url': 'https://assets.visualcv.com/images/rainier-background.jpg',
        },
        fixedStyles: {
            '@article-pike-nose-height': '2em',
            '@article-pike-nose-width': '3em',
            '@article-spacing': '150%',
            '@horizontal-spacing': '2.8em',
            '@body': '#6b6b6b',
            '@subtle': 'rgba(107, 107, 107, 0.05)',
            '@competency-size': '9px',
            '@competency-style': 'dots',
        },
    },
    fuji: {
        name: 'Fuji',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['positions', 'portfolio', 'text_story', 'dated_stories', 'strengths'],
        strengths: 'dial',
        new: true,
        styles: {
            '@header-font': 'unna',
            '@body-font': 'lato',
            '@primary': '#3e94e4',
            '@secondary': '#eaf9ff',
            '@link': '#3e94e4',
            '@background': '#ffffff',
            '@body-font-size': '16px',
            '@section-margins': '2.5em',
            '@article-margins': '2.0em',
            '@bg-url': 'https://assets.visualcv.com/images/fuji-background.jpg',
        },
        fixedStyles: {
            '@article-spacing': '150%',
            '@horizontal-spacing': '2.5em',
            '@body': '#6b6b6b',
            '@subtle': 'rgba(107, 107, 107, 0.05)',
            '@competency-size': '65px',
            '@headline-chroma-offset-x': '15px',
            '@headline-chroma-offset-y': '11px',
        },
    },
    nevis: {
        name: 'Nevis',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['summary', 'portfolio', 'text_story', 'strengths'],
        strengths: 'stripes',
        new: true,
        styles: {
            '@header-font': 'lato',
            '@body-font': 'raleway',
            '@primary': '#f1665e',
            '@secondary': '#656176',
            '@link': '#c7dfc5',
            '@background': '#ffffff',
            '@body-font-size': '14px',
            '@section-margins': '3em',
            '@article-margins': '3em',
        },
        fixedStyles: {
            '@article-spacing': '150%',
            '@horizontal-spacing': '2.2em',
            '@body': '#22293b',
            '@subtle': 'rgba(34, 41, 59, 0.05)', // @body at 5% opacity
            '@faint': '#c2d1d9',
            '@competency-style': 'stars',
        },
    },
    baker: {
        name: 'Baker',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['summary', 'portfolio', 'text_story', 'dated_stories', 'strengths'],
        strengths: 'bar-number',
        new: true,
        styles: {
            '@header-font': 'eb_garamond',
            '@body-font': 'pt_sans',
            '@primary': '#0091ff',
            '@secondary': '#dfe4e5',
            '@link': '#3e94e4',
            '@background': '#ffffff',
            '@body-font-size': '16px',
            '@section-margins': '2.5em',
            '@article-margins': '2.0em',
        },
        fixedStyles: {
            '@article-spacing': '150%',
            '@horizontal-spacing': '2.3em',
            '@body': '#6b6b6b',
            '@subtle': 'rgba(107, 107, 107, 0.05)',
            '@timeline-offset': '0.7em',
            '@article-pike-nose-height': '2.1em',
            '@article-pike-nose-width': '1.5em',
            '@competency-size': '4px',
        },
    },
    rosa: {
        name: 'Rosa',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['summary', 'degrees', 'portfolio', 'text_story', 'dated_stories', 'strengths'],
        strengths: 'bar-number',
        new: true,
        styles: {
            '@header-font': 'rasa',
            '@body-font': 'lato',
            '@primary': '#9430b1',
            '@secondary': '#f7e8fb',
            '@link': '#71128C',
            '@background': '#ffffff',
            '@body-font-size': '16px',
            '@section-margins': '2.5em',
            '@article-margins': '2.0em',
            '@bg-url': null,
        },
        fixedStyles: {
            '@article-spacing': '160%',
            '@horizontal-spacing': '6%',
            '@body': '#6b6b6b',
            '@subtle': 'rgba(107, 107, 107, 0.05)',
            '@faint': '#dedede',
            '@competency-size': '4px',
        },
    },
    bravo: {
        name: 'Bravo',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile', 'summary'],
        sidebarSections: ['degrees', 'portfolio', 'text_story', 'dated_stories', 'strengths'],
        strengths: 'bar-percentage',
        styles: {
            '@header-font': 'unna',
            '@body-font': 'pt_sans',
            '@primary': '#005799',
            '@secondary': '#c85000',
            '@link': '#c85000',
            '@background': '#fef7e5',
            '@body-font-size': '16px',
            '@section-margins': '2.2em',
            '@article-margins': '2.0em',
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': 'rgba(0, 0, 0, 0.1)',
            '@faint': '#dedede',
            '@header-spacing': '60px',
            '@competency-size': '2px',
        },
    },
    elegant: {
        name: 'Elegant',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile', 'summary'],
        sidebarSections: ['degrees', 'portfolio', 'text_story', 'dated_stories', 'strengths'],
        strengths: 'bar',
        styles: {
            '@header-font': 'eb_garamond',
            '@body-font': 'lato',
            '@primary': '#f8d232',
            '@secondary': '#000000',
            '@link': '#000000',
            '@background': '#ffffff',
            '@body-font-size': '16px',
            '@section-margins': '2.2em',
            '@article-margins': '2.0em',
        },
        fixedStyles: {
            '@header-spacing': '60px',
            '@body': '#000000',
            '@subtle': 'rgba(0, 0, 0, 0.05)',
            '@faint': '#dedede',
            '@competency-size': '4px',
        },
    },
    gallant: {
        name: 'Gallant',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['references', 'text_story'],
        strengths: 'dial',
        styles: {
            '@header-font': 'montserrat',
            '@body-font': 'rasa',
            '@primary': '#fe962f',
            '@secondary': '#555555',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '15px',
            '@section-margins': '1.5em',
            '@article-margins': '1.5em',
            '@logo-url': null,
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': 'rgba(0, 0, 0, 0.2)',
            '@faint': '#dedede',
            '@competency-size': '60px',
        },
    },
    arya: {
        name: 'Arya',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: [],
        strengths: 'stripes',
        styles: {
            '@header-font': 'ubuntu',
            '@body-font': 'pt_sans',
            '@primary': '#2cb0e5',
            '@secondary': '#000000',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '14px',
            '@section-margins': '1.4em',
            '@article-margins': '1.4em',
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': 'rgba(0, 0, 0, 0.2)',
            '@faint': '#eaeaea',
            '@competency-size': '1em',
            '@competency-style': 'dots',
        },
    },
    avant: {
        name: 'Avant',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['references', 'text_story', 'strengths'],
        strengths: 'stripes',
        styles: {
            '@header-font': 'assistant',
            '@body-font': 'assistant',
            '@primary': '#3dc1a4',
            '@secondary': '#555555',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '14px',
            '@section-margins': '3.5em',
            '@article-margins': '1.2em',
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#dedede',
            '@competency-style': 'boxes-skewed',
        },
    },
    vienna: {
        name: 'Vienna',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['text_story', 'strengths'],
        strengths: 'bar',
        styles: {
            '@header-font': 'raleway',
            '@body-font': 'raleway',
            '@primary': '#000000',
            '@secondary': '#000000',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '14px',
            '@section-margins': '1.4em',
            '@article-margins': '1.4em',
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#eaeaea',
            '@competency-size': '12px',
        },
    },
    chloe: {
        name: 'Chloe',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['text_story', 'dated_stories', 'strengths'],
        strengths: 'bar',
        styles: {
            '@header-font': 'roboto_slab',
            '@body-font': 'montserrat',
            '@primary': '#fdd0b2',
            '@secondary': '#000000',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '14px',
            '@section-margins': '2.9em',
            '@article-margins': '1.1em',
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#eeeeee',
            '@competency-size': '12px',
        },
    },
    ats: {
        name: 'ATS',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: [],
        strengths: 'bar',
        styles: {
            '@header-font': 'roboto_slab',
            '@body-font': 'montserrat',
            '@primary': '#000000',
            '@secondary': '#000000',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '14px',
            '@section-margins': '1.3em',
            '@article-margins': '1.5em',
            '@include-footer': false,
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#eaeaea',
            '@competency-size': '3px',
        },
    },
    modern: {
        name: 'Modern',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['references', 'text_story', 'strengths'],
        strengths: 'stripes',
        styles: {
            '@header-font': 'source_sans_pro',
            '@body-font': 'source_sans_pro',
            '@primary': '#ea7777',
            '@secondary': '#f2f7fb',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '15px',
            '@section-margins': '2em',
            '@article-margins': '2em',
            '@logo-url': null,
        },
        fixedStyles: {
            '@horizontal-spacing': '3.5%',
            '@body': '#000000',
            '@subtle': '#e6ebf0',
            '@faint': '#dedede',
            '@competency-style': 'boxes-skewed',
        },
    },
    brooklyn: {
        name: 'Brooklyn',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: [],
        strengths: 'bar',
        styles: {
            '@header-font': 'pt_sans',
            '@body-font': 'pt_sans',
            '@primary': '#111111',
            '@secondary': '#777777',
            '@link': '#45818e',
            '@background': '#ffffff',
            '@body-font-size': '16px',
            '@section-margins': '2em',
            '@article-margins': '1.5em',
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#777777',
            '@faint': 'rgba(0, 0, 0, 0.1)',
            '@competency-size': '6px',
        },
    },
    onyx: {
        name: 'Onyx',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: [],
        strengths: 'bar',
        styles: {
            '@header-font': 'roboto_slab',
            '@body-font': 'roboto',
            '@primary': '#64b1f2',
            '@secondary': '#ffffff',
            '@link': '#64b1f2',
            '@background': '#fcfcfc',
            '@body-font-size': '16px',
            '@section-margins': '2.5em',
            '@article-margins': '3em',
            '@bg-url': 'https://assets.visualcv.com/images/backgrounds/wood.jpg',
        },
        fixedStyles: {
            '@body': '#666666',
            '@subtle': 'rgba(255, 255, 255, 0.75)',
            '@faint': '#dedede',
            '@competency-size': '8px',
            '@competency-style': 'skewed',
        },
    },
    clair: {
        name: 'Clair',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: [],
        strengths: 'bar',
        styles: {
            '@header-font': 'source_sans_pro',
            '@body-font': 'source_sans_pro',
            '@primary': '#57a900',
            '@secondary': '#000000',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '15px',
            '@section-margins': '2em',
            '@article-margins': '0',
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#dedede',
            '@competency-size': '6px',
        },
    },
    air: {
        name: 'Air',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile', 'summary'],
        sidebarSections: [],
        strengths: 'bar',
        styles: {
            '@header-font': 'montserrat',
            '@body-font': 'montserrat',
            '@primary': '#64b1f2',
            '@secondary': '#f8f8f8',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '13px',
            '@section-margins': '1.8em',
            '@article-margins': '2.5em',
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#eeeeee',
            '@competency-size': '6px',
        },
    },
    oak: {
        name: 'Oak',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        menu: 'default',
        sidebarSections: ['references', 'text_story', 'portfolio'],
        strengths: 'bar',
        styles: {
            '@header-font': 'montserrat',
            '@body-font': 'montserrat',
            '@primary': '#bcb1cb',
            '@secondary': '#ffffff',
            '@link': '#428bca',
            '@background': '#f6f6f6',
            '@body-font-size': '15px',
            '@section-margins': '2em',
            '@article-margins': '2em',
            '@logo-url': null,
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#dedede',
            '@competency-size': '4px',
        },
    },
    monaco: {
        name: 'Monaco',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: [],
        strengths: 'bar',
        styles: {
            '@header-font': 'open_sans',
            '@body-font': 'source_sans_pro',
            '@primary': '#45818e',
            '@secondary': '#777777',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '16px',
            '@section-margins': '2.5em',
            '@article-margins': '0.7em',
            '@logo-url': null,
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#dedede',
            '@competency-size': '8px',
            '@competency-style': 'skewed',
        },
    },
    vida: {
        name: 'Vida',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile', 'summary', 'positions'],
        sidebarSections: ['degrees', 'strengths', 'text_story', 'certifications'],
        strengths: 'bar',
        styles: {
            '@header-font': 'raleway',
            '@body-font': 'roboto_slab',
            '@primary': '#fa6400',
            '@secondary': '#000000',
            '@link': '#0091FF',
            '@background': '#ffffff',
            '@body-font-size': '13px',
            '@section-margins': '2em',
            '@article-margins': '1em',
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#eeeeee',
            '@competency-size': '8px',
            '@competency-style': 'skewed',
        },
    },
    corporate: {
        name: 'Corporate',
        tier: 'professional',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['strengths', 'text_story'],
        strengths: 'bar',
        styles: {
            '@header-font': 'pt_sans',
            '@body-font': 'pt_sans',
            '@primary': '#333333',
            '@secondary': '#000000',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '14px',
            '@section-margins': '1.3em',
            '@article-margins': '2em',
            '@logo-url': null,
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#dedede',
            '@competency-size': '8px',
        },
    },
    lingo: {
        name: 'Lingo',
        tier: 'professional',
        type: 'website',
        fixedSections: ['profile'],
        sidebarSections: [],
        strengths: 'box',
        styles: {
            '@header-font': 'roboto',
            '@body-font': 'montserrat',
            '@primary': '#0a90f5',
            '@secondary': '#333333',
            '@link': '#ff3636',
            '@background': '#ffffff',
            '@body-font-size': '18px',
            '@section-margins': '2.2em',
            '@article-margins': '1.3em',
            '@bg-url': 'https://assets.visualcv.com/images/lingo-background.jpg',
        },
        fixedStyles: {
            '@competency-size': '60px',
            '@body': '#333333',
            '@subtle': 'rgba(0, 0, 0, 0.5)',
            '@faint': '#eeeeee',
        },
    },
    signal: {
        name: 'Signal',
        tier: 'professional',
        type: 'website',
        fixedSections: ['profile'],
        sidebarSections: [],
        strengths: 'dial',
        styles: {
            '@header-font': 'playfair_display',
            '@body-font': 'montserrat',
            '@primary': '#b78742',
            '@secondary': '#f0f0f0',
            '@link': '#5186cf',
            '@background': '#ffffff',
            '@body-font-size': '18px',
            '@section-margins': '2em',
            '@article-margins': '1.3em',
            '@bg-url': 'https://assets.visualcv.com/images/signal-background.jpg',
        },
        fixedStyles: {
            '@body': '#333333',
            '@subtle': 'rgba(0, 0, 0, 0.5)',
            '@faint': '#eeeeee',
            '@competency-size': '80px',
        },
    },
    verge: {
        name: 'Verge',
        tier: 'professional',
        type: 'website',
        fixedSections: ['profile'],
        sidebarSections: [],
        strengths: 'bar',
        styles: {
            '@header-font': 'oswald',
            '@body-font': 'pt_sans',
            '@primary': '#64b1f2',
            '@secondary': '#ffffff',
            '@link': '#64b1f2',
            '@background': '#000000',
            '@body-font-size': '16px',
            '@section-margins': '2.5em',
            '@article-margins': '3em',
            '@bg-url': 'https://assets.visualcv.com/images/verge.jpg',
        },
        fixedStyles: {
            '@body': '#ffffff',
            '@subtle': 'rgba(255, 255, 255, 0.75)',
            '@faint': '#dedede',
            '@competency-size': '8px',
            '@competency-style': 'skewed',
        },
    },
    about: {
        name: 'About',
        tier: 'professional',
        type: 'website',
        fixedSections: ['profile'],
        menu: 'default',
        sidebarSections: [],
        strengths: 'bar',
        styles: {
            '@header-font': 'oswald',
            '@body-font': 'pt_sans',
            '@primary': '#64b1f2',
            '@secondary': '#374b6d',
            '@link': '#64b1f2',
            '@background': '#ffffff',
            '@body-font-size': '17px',
            '@section-margins': '2.5em',
            '@article-margins': '3em',
            '@bg-url': 'https://assets.visualcv.com/images/about-background.jpg',
        },
        fixedStyles: {
            '@body': '#666666',
            '@subtle': 'rgba(255, 255, 255, 0.75)',
            '@faint': '#dedede',
            '@competency-size': '8px',
            '@competency-style': 'skewed',
        },
    },
    marketing: {
        name: 'Marketing',
        tier: 'professional',
        type: 'website',
        fixedSections: ['profile'],
        sidebarSections: [],
        strengths: 'bar',
        styles: {
            '@header-font': 'montserrat',
            '@body-font': 'roboto',
            '@primary': '#3f4147',
            '@secondary': '#22293b',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '17px',
            '@section-margins': '3em',
            '@article-margins': '3em',
            '@bg-url': 'https://assets.visualcv.com/images/backgrounds/glasses.jpg',
        },
        fixedStyles: {
            '@body': '#22293b',
            '@subtle': '#afb2bc',
            '@faint': '#dedede',
            '@competency-size': '8px',
            '@competency-style': 'skewed',
        },
    },
    monte: {
        name: 'Monte',
        tier: 'grandfathered_starter_basic',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: [],
        strengths: 'bar',
        styles: {
            '@header-font': 'roboto_slab',
            '@body-font': 'open_sans',
            '@primary': '#0b5394',
            '@secondary': '#000000',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '13px',
            '@section-margins': '1.8em',
            '@article-margins': '2.1em',
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#eeeeee',
            '@competency-size': '4px',
        },
    },
    slate: {
        name: 'Slate',
        tier: 'grandfathered_starter_basic',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: ['references', 'text_story', 'strengths', 'portfolio'],
        strengths: 'stripes',
        styles: {
            '@header-font': 'source_sans_pro',
            '@body-font': 'open_sans',
            '@body-font-size': '14px',
            '@primary': '#e05900',
            '@secondary': '#000000',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@section-margins': '3em',
            '@article-margins': '1.8em',
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#dedede',
            '@competency-style': 'boxes-skewed',
        },
    },
    standard: {
        name: 'Standard',
        tier: 'grandfathered_starter_basic_standard',
        type: 'resume',
        fixedSections: ['profile'],
        sidebarSections: [],
        strengths: 'stripes',
        styles: {
            '@header-font': 'pt_serif',
            '@body-font': 'open_sans',
            '@primary': '#333333',
            '@secondary': '#777777',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '15px',
            '@section-margins': '3em',
            '@article-margins': '2.2em',
        },
        fixedStyles: {
            '@body': '#000000',
            '@subtle': '#cccccc',
            '@faint': '#dedede',
            '@competency-style': 'boxes-skewed',
        },
    },
    cl1: {
        name: 'Cover Letter',
        tier: 'free',
        type: 'cover_letter',
        fixedSections: [],
        sidebarSections: [],
        styles: {
            '@body-font': 'assistant',
            '@link': '#428bca',
            '@background': '#ffffff',
            '@body-font-size': '16px',
            '@article-margins': '1.5em',
        },
        fixedStyles: {
            '@body': '#000000',
        },
    },
}